server:
  port: 9002
#jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/ipgo/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: 1234
mybatis:
  type-aliases-package: boot.*   
  mapper-locations:
  - /mapper/**/*.xml

